encantodedoce/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using encantodedoce.Models;
using PagedList;

namespace encantodedoce.Controllers
{
    public class ClienteController : Controller
    {
        private DBConnect db = new DBConnect();

        // GET: Cliente
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.nmCliente = String.IsNullOrEmpty(sortOrder) ? "nmCliente_desc" : "";
            ViewBag.dsEmail = sortOrder == "dsEmail" ? "dsEmail_desc" : "dsEmail";

            //Paginação
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var cliente = from s in db.cliente
                           select s;

            //Busca
            if (!String.IsNullOrEmpty(searchString))
            {
                cliente = cliente.Where(s => s.nmCliente.Contains(searchString)
                                       || s.dsEmail.Contains(searchString)
                                       || s.nrTelefone.Contains(searchString));
            }

            //Ordenação
            switch (sortOrder)
            {
                case "nmCliente_desc":
                    cliente = cliente.OrderByDescending(s => s.nmCliente);
                    break;
                case "dsEmail":
                    cliente = cliente.OrderBy(s => s.dsEmail);
                    break;
                case "dsEmail_desc":
                    cliente = cliente.OrderByDescending(s => s.dsEmail);
                    break;
                default:
                    cliente = cliente.OrderBy(s => s.nmCliente);
                    break;
            }

            //Exibe 10 registros por página
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(cliente.ToPagedList(pageNumber, pageSize));
        }

        // GET: Cliente/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cliente cliente = await db.cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idCliente,nmCliente,nrTelefone,dsEndereco,dsEmail,dtInclusao,dtAlteracao")] cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.dtInclusao = DateTime.Now;

                db.cliente.Add(cliente);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        // GET: Cliente/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cliente cliente = await db.cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idCliente,nmCliente,nrTelefone,dsEndereco,dsEmail,dtInclusao,dtAlteracao")] cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.dtAlteracao = DateTime.Now;

                db.Entry(cliente).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cliente cliente = await db.cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            cliente cliente = await db.cliente.FindAsync(id);
            db.cliente.Remove(cliente);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

encantodedoce/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using encantodedoce.Models;
using PagedList;

namespace encantodedoce.Controllers
{
    public class PedidoController : Controller
    {
        private DBConnect db = new DBConnect();

        // GET: Pedido
        //public async Task<ActionResult> Index()
        //{
        //    var pedido = db.pedido.Include(p => p.cliente);
        //    return View(await pedido.ToListAsync());
        //}

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.nmCliente = String.IsNullOrEmpty(sortOrder) ? "nmCliente_desc" : "";

            //Paginação
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            db.cliente.Include(p => p.pedidos);

            var pedidos = from p in db.pedido
                           select p;

            //Busca
            if (!String.IsNullOrEmpty(searchString))
            {
                //pedidos = pedidos.Where(p => p..Contains(searchString));
            }

            //Ordenação
            switch (sortOrder)
            {
                case "nmCliente_desc":
                    pedidos = pedidos.OrderByDescending(p => p.idPedido);
                    break;
                default:
                    pedidos = pedidos.OrderBy(p => p.idPedido);
                    break;
            }

            //Exibe 10 registros por página
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(pedidos.ToPagedList(pageNumber, pageSize));

        }

        // GET: Pedido/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pedido pedido = await db.pedido.FindAsync(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // GET: Pedido/Create
        public ActionResult Create()
        {
            
            ViewBag.idCliente = new SelectList(db.cliente, "idCliente", "nmCliente");
            ViewBag.idProduto = new SelectList(db.produto, "idProduto", "nmProduto");

            return View();
        }

        // POST: Pedido/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idPedido,idCliente,valorTotal,dsPedido,bolPago,dtInclusao,dtAlteracao")] pedido pedido)
        {
            if (ModelState.IsValid)
            {
                pedido.dtInclusao = DateTime.Now;
                
                db.pedido.Add(pedido);
                await db.SaveChangesAsync();
                
                return RedirectToAction("Index");
            }

            ViewBag.idCliente = new SelectList(db.cliente, "idCliente", "nmCliente", pedido.idCliente);
            return View(pedido);
        }

        // GET: Pedido/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pedido pedido = await db.pedido.FindAsync(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCliente = new SelectList(db.cliente, "idCliente", "nmCliente", pedido.idCliente);
            return View(pedido);
        }

        // POST: Pedido/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idPedido,idCliente,valorTotal,dsPedido,bolPago,dtInclusao,dtAlteracao")] pedido pedido)
        {
            if (ModelState.IsValid)
            {
                pedido.dtAlteracao = DateTime.Now;

                db.Entry(pedido).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idCliente = new SelectList(db.cliente, "idCliente", "nmCliente", pedido.idCliente);
            return View(pedido);
        }

        // GET: Pedido/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pedido pedido = await db.pedido.FindAsync(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            pedido pedido = await db.pedido.FindAsync(id);
            db.pedido.Remove(pedido);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

encantodedoce/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using encantodedoce.Models;
using PagedList;

namespace encantodedoce.Controllers
{
    public class ProdutoController : Controller
    {
        private DBConnect db = new DBConnect();

        // GET: Produto
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.nmProduto = String.IsNullOrEmpty(sortOrder) ? "nmProduto_desc" : "";

            //Paginação
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            db.produto.Include(p => p.tipoProduto);

            var produtos = from p in db.produto
                           select p;

            //Busca
            if (!String.IsNullOrEmpty(searchString))
            {
                produtos = produtos.Where(p => p.nmProduto.Contains(searchString));
            }

            //Ordenação
            switch (sortOrder)
            {
                case "nmProduto_desc":
                    produtos = produtos.OrderByDescending(p => p.nmProduto);
                    break;
                default:
                    produtos = produtos.OrderBy(p => p.nmProduto);
                    break;
            }

            //Exibe 10 registros por página
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(produtos.ToPagedList(pageNumber, pageSize));

        }

        // GET: Produto/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            produto produto = await db.produto.FindAsync(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            ViewBag.idTipoProduto = new SelectList(db.tipoProduto, "idTipoProduto", "nmTipoProduto");
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idProduto,idTipoProduto,nmProduto,precoProduto,pesoProduto,dsProduto,dtInclusao,dtAlteracao")] produto produto)
        {
            if (ModelState.IsValid)
            {
                produto.dtInclusao = DateTime.Now;

                db.produto.Add(produto);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.idTipoProduto = new SelectList(db.tipoProduto, "idTipoProduto", "nmTipoProduto", produto.idTipoProduto);
            return View(produto);
        }

        // GET: Produto/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            produto produto = await db.produto.FindAsync(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.idTipoProduto = new SelectList(db.tipoProduto, "idTipoProduto", "nmTipoProduto", produto.idTipoProduto);
            return View(produto);
        }

        // POST: Produto/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idProduto,idTipoProduto,nmProduto,precoProduto,pesoProduto,dsProduto,dtInclusao,dtAlteracao")] produto produto)
        {
            if (ModelState.IsValid)
            {
                produto.dtAlteracao = DateTime.Now;

                db.Entry(produto).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idTipoProduto = new SelectList(db.tipoProduto, "idTipoProduto", "nmTipoProduto", produto.idTipoProduto);
            return View(produto);
        }

        // GET: Produto/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            produto produto = await db.produto.FindAsync(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            produto produto = await db.produto.FindAsync(id);
            db.produto.Remove(produto);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

encantodedoce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Encanto de Doce</title>
    <!-- Bootstrap core CSS-->
    @Styles.Render("~/Scripts/vendor/bootstrap/css/bootstrap.min.css")
    <!-- Custom fonts for this template-->
    @Styles.Render("~/Scripts/vendor/font-awesome/css/font-awesome.min.css")
    <!-- Page level plugin CSS-->
    @Styles.Render("~/Scripts/vendor/datatables/dataTables.bootstrap4.css")
    <!-- Custom styles for this template-->
    @Styles.Render("~/Scripts/css/sb-admin.css")
    <!-- Custom styles for this pagination-->
    @Styles.Render("~/Scripts/css/PagedList.css")


</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="index.html">Encanto de Doce</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="index.html">
                        <i class="fa fa-fw fa-dashboard"></i>
                        <span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponentsPedidos" data-parent="#exampleAccordion">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">Pedidos</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapseComponentsPedidos">
                        <li>
                            @Html.ActionLink("Pesquisar", "Index", "Pedido")
                        </li>
                        <li>
                            @Html.ActionLink("Incluir", "Create", "Pedido")
                        </li>
                    </ul>
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponentsClientes" data-parent="#exampleAccordion">
                        <i class="fa fa-fw fa-user"></i>
                        <span class="nav-link-text">Clientes</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapseComponentsClientes">
                        <li>
                            @Html.ActionLink("Pesquisar", "Index", "Cliente")
                        </li>
                        <li>
                            @Html.ActionLink("Incluir", "Create", "Cliente")
                        </li>
                    </ul>
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponentsProdutos" data-parent="#exampleAccordion">
                        <i class="fa fa-fw fa-shopping-bag"></i>
                        <span class="nav-link-text">Produtos</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapseComponentsProdutos">
                        <li>
                            @Html.ActionLink("Pesquisar", "Index", "Produto")
                        </li>
                        <li>
                            @Html.ActionLink("Incluir", "Create", "Produto")
                        </li>
                    </ul>
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponentsTipoProdutos" data-parent="#exampleAccordion">
                        <i class="fa fa-fw fa-list"></i>
                        <span class="nav-link-text">Tipos de Produto</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapseComponentsTipoProdutos">
                        <li>
                            @Html.ActionLink("Pesquisar", "Index", "TipoProduto")
                        </li>
                        <li>
                            @Html.ActionLink("Incluir", "Create", "TipoProduto")
                        </li>
                    </ul>
                </li>

            </ul>
            <ul class="navbar-nav sidenav-toggler">
                <li class="nav-item">
                    <a class="nav-link text-center" id="sidenavToggler">
                        <i class="fa fa-fw fa-angle-left"></i>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0 mr-lg-2">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Procurar um Pedido...">
                            <span class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out"></i>Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="content-wrapper">
        <div class="container-fluid">

            <!-- Contents -->
            @RenderBody()

        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Copyright © Encanto de Doce 2018</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    @Scripts.Render("~/Scripts/vendor/jquery/jquery.min.js")
    @Scripts.Render("~/Scripts/vendor/bootstrap/js/bootstrap.bundle.min.js")
    <!-- Core plugin JavaScript-->
    @Scripts.Render("~/Scripts/vendor/jquery-easing/jquery.easing.min.js")
    <!-- Page level plugin JavaScript-->
    @Scripts.Render("~/Scripts/vendor/chart.js/Chart.min.js")
    @Scripts.Render("~/Scripts/vendor/datatables/jquery.dataTables.js")
    @Scripts.Render("~/Scripts/vendor/datatables/dataTables.bootstrap4.js")
    <!-- Custom scripts for all pages-->
    @Scripts.Render("~/Scripts/js/sb-admin.min.js")
    <!-- Custom scripts for this page-->
    @Scripts.Render("~/Scripts/js/sb-admin-datatables.min.js")
    @Scripts.Render("~/Scripts/js/sb-admin-charts.min.js")
    <!-- scripts for mask input-->
    @Scripts.Render("~/Scripts/vendor/mask/jquery.maskedinput.min.js")

    @RenderSection("scripts", false)
</body>
</html>