encantodedoce/Models/pedido.cs
namespace encantodedoce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("pedido")]
    public partial class pedido
    {       
        public pedido()
        {
            pedidosEfetuados = new HashSet<pedidoEfetuado>();
        }

        [Key]
        public int idPedido { get; set; }

        public int? idCliente { get; set; }

        public decimal? valorTotal { get; set; }

        [Column(TypeName = "text")]
        public string dsPedido { get; set; }

        public bool? bolPago { get; set; }

        public DateTime dtInclusao { get; set; }

        public DateTime? dtAlteracao { get; set; }

        public virtual cliente cliente { get; set; }
                
        public virtual ICollection<pedidoEfetuado> pedidosEfetuados { get; set; }
    }
}

encantodedoce/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using encantodedoce.Models;
using PagedList;

namespace encantodedoce.Controllers
{
    public class PedidoController : Controller
    {
        private DBConnect db = new DBConnect();

        // GET: Pedido
        //public async Task<ActionResult> Index()
        //{
        //    var pedido = db.pedido.Include(p => p.cliente);
        //    return View(await pedido.ToListAsync());
        //}

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.nmCliente = String.IsNullOrEmpty(sortOrder) ? "nmCliente_desc" : "";

            //Paginação
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            db.cliente.Include(p => p.pedidos);

            var pedidos = from p in db.pedido
                           select p;

            //Busca
            if (!String.IsNullOrEmpty(searchString))
            {
                //pedidos = pedidos.Where(p => p..Contains(searchString));
            }

            //Ordenação
            switch (sortOrder)
            {
                case "nmCliente_desc":
                    pedidos = pedidos.OrderByDescending(p => p.idPedido);
                    break;
                default:
                    pedidos = pedidos.OrderBy(p => p.idPedido);
                    break;
            }

            //Exibe 10 registros por página
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(pedidos.ToPagedList(pageNumber, pageSize));

        }

        // GET: Pedido/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pedido pedido = await db.pedido.FindAsync(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // GET: Pedido/Create
        public ActionResult Create()
        {
            
            ViewBag.idCliente = new SelectList(db.cliente, "idCliente", "nmCliente");
            ViewBag.idProduto = new SelectList(db.produto, "idProduto", "nmProduto");

            return View();
        }

        // POST: Pedido/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idPedido,idCliente,valorTotal,dsPedido,bolPago,dtInclusao,dtAlteracao")] pedido pedido)
        {
            if (ModelState.IsValid)
            {
                pedido.dtInclusao = DateTime.Now;
                
                db.pedido.Add(pedido);
                await db.SaveChangesAsync();
                
                return RedirectToAction("Index");
            }

            ViewBag.idCliente = new SelectList(db.cliente, "idCliente", "nmCliente", pedido.idCliente);
            return View(pedido);
        }

        // GET: Pedido/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pedido pedido = await db.pedido.FindAsync(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCliente = new SelectList(db.cliente, "idCliente", "nmCliente", pedido.idCliente);
            return View(pedido);
        }

        // POST: Pedido/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idPedido,idCliente,valorTotal,dsPedido,bolPago,dtInclusao,dtAlteracao")] pedido pedido)
        {
            if (ModelState.IsValid)
            {
                pedido.dtAlteracao = DateTime.Now;

                db.Entry(pedido).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idCliente = new SelectList(db.cliente, "idCliente", "nmCliente", pedido.idCliente);
            return View(pedido);
        }

        // GET: Pedido/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pedido pedido = await db.pedido.FindAsync(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            pedido pedido = await db.pedido.FindAsync(id);
            db.pedido.Remove(pedido);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

encantodedoce/Controllers/tipoProdutoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using encantodedoce.Models;
using PagedList;

namespace encantodedoce.Controllers
{
    public class TipoProdutoController : Controller
    {
        private DBConnect db = new DBConnect();

        // GET: TipoProdutossss
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.tipoProduto = String.IsNullOrEmpty(sortOrder) ? "tipoProduto" : "";

            //Paginação
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var tipoProdutos = from s in db.tipoProduto
                               select s;

            //Busca
            if (!String.IsNullOrEmpty(searchString))
            {
                tipoProdutos = tipoProdutos.Where(s => s.nmTipoProduto.Contains(searchString));
            }

            //Ordenação
            switch (sortOrder)
            {
                case "tipoProduto":
                    tipoProdutos = tipoProdutos.OrderByDescending(s => s.nmTipoProduto);
                    break;
                default:
                    tipoProdutos = tipoProdutos.OrderBy(s => s.nmTipoProduto);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(tipoProdutos.ToPagedList(pageNumber, pageSize));
        }

        // GET: TipoProduto/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tipoProduto tipoProduto = await db.tipoProduto.FindAsync(id);
            if (tipoProduto == null)
            {
                return HttpNotFound();
            }
            return View(tipoProduto);
        }

        // GET: TipoProduto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoProduto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idTipoProduto,nmTipoProduto,dtInclusao,dtAlteracao")] tipoProduto tipoProduto)
        {
            if (ModelState.IsValid)
            {
                tipoProduto.dtInclusao = DateTime.Now;

                db.tipoProduto.Add(tipoProduto);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(tipoProduto);
        }

        // GET: TipoProduto/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tipoProduto tipoProduto = await db.tipoProduto.FindAsync(id);
            if (tipoProduto == null)
            {
                return HttpNotFound();
            }
            return View(tipoProduto);
        }

        // POST: TipoProduto/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idTipoProduto,nmTipoProduto,dtInclusao,dtAlteracao")] tipoProduto tipoProduto)
        {
            if (ModelState.IsValid)
            {
                tipoProduto.dtAlteracao = DateTime.Now;

                db.Entry(tipoProduto).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(tipoProduto);
        }

        // GET: TipoProduto/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tipoProduto tipoProduto = await db.tipoProduto.FindAsync(id);
            if (tipoProduto == null)
            {
                return HttpNotFound();
            }
            return View(tipoProduto);
        }

        // POST: TipoProduto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            tipoProduto tipoProduto = await db.tipoProduto.FindAsync(id);
            db.tipoProduto.Remove(tipoProduto);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

encantodedoce/Views/pedido/Create.cshtml
@model encantodedoce.Models.pedido

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Adicionar Pedido</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2" for="idCliente">Cliente:</label>
        <div class="col-md-10">
            @Html.DropDownList("idCliente", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idCliente, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="dsPedido">Descrição do Pedido:</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.dsPedido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dsPedido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="bolPago">Foi pago?</label>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.bolPago)
                @Html.ValidationMessageFor(model => model.bolPago, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="idProduto">Selecione os Produtos:</label>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.DropDownList("idProduto", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="bolPago">Quantidade:</label>
        <div class="col-md-2">
            <div class="checkbox">
                <input type="text" class="form-control" id="qnt">
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <div class="table-responsive">
                <table class="table table-bordered" id="" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nome Produto</th>
                            <th>Qnt</th>
                            <th>Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="width:20%">Nome Produto</td>
                            <td style="width:10%">Qnt</td>
                            <td style="width:5%">
                                <div class="form-row">
                                    <div class="margin-1px">
                                        <input type="submit" value="Remover" class="btn btn-danger" />
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-primary" />
            @Html.ActionLink("Voltar para Lista", "Index", "TipoProduto", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>
}

encantodedoce/Views/pedido/Delete.cshtml
@model encantodedoce.Models.pedido

@{
    ViewBag.Title = "Excluir Pedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Excluir Pedido</h3>

<div class="alert alert-warning" role="alert">
    <h5>Tem certeza que deseja excluir este registro?</h5>
</div>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nome do Cliente:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cliente.nmCliente)
        </dd>

        <dt>
            Valor Total:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.valorTotal)
        </dd>

        <dt>
            Descrição Do Pedido:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsPedido)
        </dd>

        <dt>
            Foi pago?
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bolPago)
        </dd>

        <dt>
            Data de Inclusão:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtInclusao)
        </dd>

        <dt>
            Data de Alteração:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtAlteracao)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" />
            @Html.ActionLink("Voltar para Lista", "Index", "Pedido", null, new { @class = "btn btn-secondary" })
        </div>
    }   
</div>

encantodedoce/Views/pedido/Details.cshtml
@model encantodedoce.Models.pedido

@{
    ViewBag.Title = "Detalhes do Pedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Detalhes do Pedido</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nome do Cliente:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cliente.nmCliente)
        </dd>

        <dt>
            Valor Total:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.valorTotal)
        </dd>

        <dt>
            Descrição Do Pedido:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsPedido)
        </dd>

        <dt>
            Foi pago?
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bolPago)
        </dd>

        <dt>
            Data de Inclusão:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtInclusao)
        </dd>

        <dt>
            Data de Alteração:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtAlteracao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "edit", "Pedido", new { id = Model.idPedido }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar para Lista", "Index", "Pedido", null, new { @class = "btn btn-secondary" })
</p>

encantodedoce/Views/pedido/Edit.cshtml
@model encantodedoce.Models.pedido

@{
    ViewBag.Title = "Editar Pedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Editar Pedido</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idPedido)
    @Html.HiddenFor(model => model.dtInclusao)

    <div class="form-group">
        <label class="control-label col-md-2" for="idCliente">Cliente:</label>
        <div class="col-md-10">
            @Html.DropDownList("idCliente", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idCliente, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="valorTotal">Valor Total:</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.valorTotal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.valorTotal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="dsPedido">Descrição do Pedido:</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.dsPedido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dsPedido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="bolPago">Foi pago?</label>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.bolPago)
                @Html.ValidationMessageFor(model => model.bolPago, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-primary" />
            @Html.ActionLink("Voltar para Lista", "Index", "Pedido", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>
}

encantodedoce/Views/pedido/Index.cshtml
@model PagedList.IPagedList<encantodedoce.Models.pedido>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Lista de Pedidos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Lista de Pedidos</h3>

<div class="card-body">
    <form>
        <div class="form-group">
            <div class="form-row">
                @using (Html.BeginForm("Index", "Pedido", FormMethod.Get))
                {
                    <div class="col-md-4">
                        <div class="input-group">
                            @Html.Editor("SearchString", ViewBag.CurrentFilter as string, new { htmlAttributes = new { @class = "form-control" } })
                            <span class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                }
                <div class="col-md-1 margin-1px">
                    @Html.ActionLink("Novo", "Create", "Pedido", null, new { @class = "btn btn-primary btn-block" })
                </div>
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table table-bordered" id="" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>@Html.ActionLink("Cliente", "Index", new { sortOrder = ViewBag.nmCliente, currentFilter = ViewBag.CurrentFilter })</th>
                    <th>Valor Total</th>
                    <th>Desc. Pedido</th>
                    <th>Pago</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td style="width:20%">@Html.DisplayFor(modelItem => item.cliente.nmCliente)</td>
                    <td style="width:10%">@Html.DisplayFor(modelItem => item.valorTotal)</td>
                    <td>@Html.DisplayFor(modelItem => item.dsPedido)</td>
                    <td style="width:10%">@Html.DisplayFor(modelItem => item.bolPago)</td>
                    <td style="width:18%">
                        <div class="form-row">
                            <div class="margin-1px">
                                @Html.ActionLink("Editar", "Edit", "Pedido", new { id = item.idPedido }, new { @class = "btn btn-primary" })
                            </div>
                            <div class="margin-1px">
                                @Html.ActionLink("Detalhe", "Details", "Pedido", new { id = item.idPedido }, new { @class = "btn btn-primary" })
                            </div>
                            <div class="margin-1px">
                                @Html.ActionLink("Excluir", "Delete", "Pedido", new { id = item.idPedido }, new { @class = "btn btn-danger" })
                            </div>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    <div>
        Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index",
                                         new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
</div>